[pytest]
# addopts 等同于你在命令行手动输入 -vs
# -s: 不拦截控制台输出 (重要：看到 SEND/RECV 就靠它)
# -v: 详细模式
addopts = -s -v --color=yes --basetemp=test_cache

# 如果你想在 VS Code 的 "Output" 窗口看到实时日志，还可以加上这些：
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s
log_cli_date_format=%H:%M:%S

pythonpath = .

pytest_plugins = ["test.fixture.nvs_fixtures"]

# 规定金库总目录的名字
vault_folder_name = nvs_test_vaults
